### ISSUE TITLE
define color scale

### ISSUE THREAD

**Issue by ykcheung** [ursudio/leaflet-webgl-heatmap#19]
Hi thank you for your work ! It is really beautiful. 

I wanna define my own color scale base on the intensity of each point. 
![my color scale](https://cloud.githubusercontent.com/assets/5967220/23010029/457227f4-f454-11e6-8e2a-400b947a2a5b.png)

Is this possible ?

**Comment by bozdoz** [comment]
Have you seen the `gradientTexture` option?  Pass an image or path to an image.  See some of the PNGs on the webgl heatmap library repo: https://github.com/pyalot/webgl-heatmap. Does that work for you?

**Comment by ykcheung** [comment]
Oic thank you !
