### ISSUE TITLE
npm package is broken

### ISSUE THREAD

**Issue by autowp** [ursudio/leaflet-webgl-heatmap#21]
There is no js files
```
$ npm install leaflet-webgl-heatmap --save 
example@0.0.1 /home/example
└── leaflet-webgl-heatmap@0.2.2

$ ls node_modules/leaflet-webgl-heatmap/
LICENSE.md  package.json  README.md
```

**Comment by bozdoz** [comment]
Yeah, not sure what happened.  Can't seem to fix it with a republish.  Any ideas, yourself?

**Comment by bozdoz** [comment]
Think I found it.  Guess the `files` keyword in `package.json` shouldn't start with `'./'`.  Let me know if you still have trouble.
