### ISSUE TITLE
Missing _destroyContainer function

### ISSUE THREAD

**Issue by chriswilley** [ursudio/leaflet-webgl-heatmap#22]
On Feb 2, Leaflet introduced a change to Renderer.js' onRemove() function that calls `this._destroyContainer();`. You can [see the commit detail here](https://github.com/Leaflet/Leaflet/commit/14c5f1602cdd337df14c37ea8df777578219f744). I think the authors assumed that plugins would inherit from SVG or Canvas rather than Renderer directly, as Renderer does not have a _destroyContainer function (but the two subclasses each have one).

At that point (I believe), plugins inheriting from Renderer began to fail when onRemove() is called. In any case, that's what started happening to me when I upgraded Leaflet to 1.1.0. I was able to resolve the problem by adding the following code to src/leaflet-webgl-heatmap.js (copied mostly verbatim from Leaflet's Canvas.js current source code, although I had to call "L.DomUtil" and "L.DomEvent" as Leaflet has since removed calls to L in its modules) and then running "gulp build":

```
_destroyContainer: function () {
    delete this._ctx;
    L.DomUtil.remove(this._container);
    L.DomEvent.off(this._container);
    delete this._container;
},
```

I am using this plugin in an Angular2 project, so I am not sure if folks using JavaScript rather than TypeScript are seeing this (the plugin failed with a TypeError).

I'm posting this code rather than making a PR as I'm not sure this is the right long term fix. Maybe the plugin should inherit from L.Canvas?

Hope this helps someone!

**Comment by bozdoz** [comment]
Thanks! I put your name in the package.json as a contributor.  Feel free to edit if you care.
